// Code generated by scripts/ts2go.js from src\components\counter.new.ts; DO NOT EDIT.
package components

import ssr "signals-ssr"
type CounterProps struct {
	Label any
}
// Counter is a generated View from a TS html template.
func Counter() ssr.View {
	return CounterWithProps(CounterProps{})
}
func CounterWithProps(props CounterProps) ssr.View {
	return ssr.HTML([]string{"<div class=\"card\">\n        <button type=\"button\" onclick=\"", "\" oncontextmenu=\"", "\">\n            ", ": ", " (x2: ", ")\n        </button>\n    </div>"}, "handleClick", "handleRightClick", props.Label, 0, 0)
}
