// Code generated by scripts/ts2go.js from src\components\list-item.new.ts; DO NOT EDIT.
package components

import ssr "signals-ssr"
type ListItemProps struct {
	Text any
}
// ListItem is a generated View from a TS html template.
func ListItem() ssr.View {
	return ListItemWithProps(ListItemProps{})
}
func ListItemWithProps(props ListItemProps) ssr.View {
	return ssr.HTML([]string{"<li>", "</li>"}, props.Text)
}
